sequenceDiagram
    alt get all employees
        CLIENT->>API: GET /employees
    else get employee by id
        CLIENT->>API: GET /employees/{id:int}
    else create employee 
        CLIENT->>API: POST /employees
    else update employee by id
        CLIENT->>API: PUT /employees/{id:int}
    else delete employee by id
        CLIENT->>+API: DELETE /employees/{id:int}
    end
    alt mapping
        API->>API: JSON to SOAP
    end
    API->>+SOAP: SOAP request
    alt rpc
        SOAP->>SOAP: get, getAll, create, update and delete
    end
    SOAP-->>-API: SOAP result
    alt mapping
        API->>API: SOAP to JSON
    end
    API-->>-CLIENT: http result
    Note over API,CLIENT: payload: JSON<br>http status: 200 OK, 201 Created,<br>202 Accepted, 404 Not Found,<br>405 Method not allowed
    Note right of SOAP: legacy role
    Note over API,SOAP: IBM Integration Bus