sequenceDiagram
    alt get all employees
        CLIENT->>API: GET /employees
    else get employee by id
        CLIENT->>API: GET /employees/{id:int}
    else create employee 
        CLIENT->>API: POST /employees
    else update employee by id
        CLIENT->>API: PUT /employees/{id:int}
    else delete employee by id
        CLIENT->>+API: DELETE /employees/{id:int}
    end
    alt mapping
        API->>API: JSON to SOAP
    end
    API->>+SOAP: SOAP request
    alt rpc
        SOAP->>SOAP: get, create, update and delete
    end
    SOAP-->>-API: SOAP result
    alt mapping
        API->>API: SOAP to JSON
    end
    API-->>-CLIENT: 200 Ok, 201 Created, 202 Accepted, 404 Not Found
    Note right of SOAP: legacy role
    Note over API,SOAP: IBM Integration Bus